version: '3.5'
services: 
    smb-webmin:
        container_name: ${CONTAINER_NAME_SAMBA}
        restart: unless-stopped
        image: dejan995/smbwebmin-docker:latest
        hostname: ${SAMBA_HOSTNAME}
        ports:
            - ${SAMBA_WEBUI_PORT}:10000
            - 137:137/udp
            - 138:138/udp
            - 139:139
            - 445:445
        volumes: 
            - ${SMBWEBMIN_CONFIG}:/data
            - ${ROOT_SHARE_FOLDER}:/mnt
        environment: 
            - WEBMIN_PASSWORD=${WEBMIN_PASSWORD}