version: '3.5'
services: 
    smb-webmin:
        build:
            context: .
        restart: unless-stopped
        image: smbwebmin:latest
        hostname: ${SAMBA_HOSTNAME}
        ports:
            - ${SAMBA_WEBUI_PORT}:10000
            - 137:137/udp
            - 138:138/udp
            - 139:139
            - 445:445
        volumes: 
            - ${SMBWEBMIN_CONFIG}:/data
            - ${ROOT_SHARE_FOLDER}:/mnt
        environment: 
            - WEBMIN_LOGIN=${WEBMIN_LOGIN}  
            - WEBMIN_PASSWORD=${WEBMIN_PASSWORD}