version: '3.5'
services: 
    smb-webmin:
        container_name: ${CONTAINER_NAME_SAMBA}
        restart: unless-stopped
        image: dejan995/smbwebmin-docker:latest
        hostname: ${SAMBA_HOSTNAME}
        ports:
            - ${SAMBA_WEBUI_PORT}:10000
            - 137:137/udp
            - 138:138/udp
            - 139:139
            - 445:445
        volumes: 
            - etc_webmin:/etc/webmin
            - etc_samba:/etc/samba
            - var_lib_samba:/var/lib/samba
            - ${ROOT_SHARE_FOLDER}:/mnt
        environment: 
            - WEBMIN_PASSWORD=${WEBMIN_PASSWORD}

volumes:
    etc_webmin:
      driver: local
      driver_opts:
        type: none
        device: ${ETC_WEBMIN}
        o: bind
    etc_samba:
        driver: local
        driver_opts: 
            type: none
            device: ${ETC_SAMBA}
            o: bind
    var_lib_samba:
        driver: local
        driver_opts: 
            type: none
            device: ${VAR_LIB_SAMBA}
            o: bind