trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -u $(username):$(password) https://jenkins.dapmn.com/job/smbwebmin-docker/build?token=$(token)
  displayName: 'Triggering Jenkins build for smbwebmin-docker'
